{"exception":{"stacktrace":"java.net.BindException: Address already in use: bind\n\tat sun.nio.ch.Net.bind0(Native Method)\n\tat sun.nio.ch.Net.bind(Net.java:433)\n\tat sun.nio.ch.Net.bind(Net.java:425)\n\tat sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)\n\tat io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)\n\tat io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)\n\tat io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1346)\n\tat io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)\n\tat io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)\n\tat io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:985)\n\tat io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)\n\tat io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:344)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute$$$capture(AbstractEventExecutor.java:163)\n\tat io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)","exception_class":"java.net.BindException","exception_message":"Address already in use: bind"},"source_host":"DESKTOP-LDGMM05","method":"start","level":"ERROR","message":" [DUBBO] qos-server can not bind localhost:22222, dubbo version: 2.7.3, current host: 169.254.98.54","mdc":{},"@timestamp":"2019-10-24T09:50:07.463Z","file":"Server.java","application":"service_product_new","line_number":"103","thread_name":"main","@version":1,"logger_name":"org.apache.dubbo.qos.server.Server","class":"org.apache.dubbo.qos.server.Server"}
{"exception":{"stacktrace":"org.apache.dubbo.remoting.RemotingException: client(url: dubbo:\/\/172.17.251.242:20880\/com.overstar.order.export.api.IOrderService?anyhost=true&application=open-export&bean.name=iOrderService&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=base-service&heartbeat=60000&interface=com.overstar.order.export.api.IOrderService&lazy=false&methods=cancel,cancelBySso,cancelFailed,confirmFinishBySso,deleteBatch,cancelFinished,cancelByQuartz,confirmFinish,getBySn,getById,confirmFinishByQuartz,create,notifyPayed,orderCountBySso,sendShip&pid=17692&register=true&register.ip=169.254.98.54&release=2.7.3&remote.application=order&retries=0&revision=0.0.1-SNAPSHOT&service.filter=dubboServer&side=consumer&sticky=false&timeout=20000&timestamp=1571915159317&version=0.0.1) failed to connect to server \/172.17.251.242:20880, error message is:Connection refused: no further information: \/172.17.251.242:20880\n\tat org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:166)\n\tat org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:190)\n\tat org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:246)\n\tat org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:155)\n\tat org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)\n\tat org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)\n\tat org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)\n\tat org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)\n\tat org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)\n\tat java.lang.Thread.run(Thread.java:748)\nCaused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: \/172.17.251.242:20880\nCaused by: java.net.ConnectException: Connection refused: no further information\n\tat sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)\n\tat sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)\n\tat io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:327)\n\tat io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:688)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)\n\tat io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)\n\tat io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)\n\tat io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)\n\tat io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)\n\tat io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)\n\tat java.lang.Thread.run(Thread.java:748)","exception_class":"org.apache.dubbo.remoting.RemotingException","exception_message":"client(url: dubbo:\/\/172.17.251.242:20880\/com.overstar.order.export.api.IOrderService?anyhost=true&application=open-export&bean.name=iOrderService&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=base-service&heartbeat=60000&interface=com.overstar.order.export.api.IOrderService&lazy=false&methods=cancel,cancelBySso,cancelFailed,confirmFinishBySso,deleteBatch,cancelFinished,cancelByQuartz,confirmFinish,getBySn,getById,confirmFinishByQuartz,create,notifyPayed,orderCountBySso,sendShip&pid=17692&register=true&register.ip=169.254.98.54&release=2.7.3&remote.application=order&retries=0&revision=0.0.1-SNAPSHOT&service.filter=dubboServer&side=consumer&sticky=false&timeout=20000&timestamp=1571915159317&version=0.0.1) failed to connect to server \/172.17.251.242:20880, error message is:Connection refused: no further information: \/172.17.251.242:20880"},"source_host":"DESKTOP-LDGMM05","method":"doTask","level":"ERROR","message":" [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [169.254.98.54:0 -> \/172.17.251.242:20880]], dubbo version: 2.7.3, current host: 169.254.98.54","mdc":{},"@timestamp":"2019-10-24T12:22:22.122Z","file":"ReconnectTimerTask.java","application":"service_product_new","line_number":"51","thread_name":"dubbo-client-idleCheck-thread-1","@version":1,"logger_name":"org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask","class":"org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask"}
